---
- name: checking if httpd is install
  command: rpm -q httpd
  args:
    warn: False
  register: is_installed
  failed_when: is_installed.rc > 1


- name: is https installed?
  debug: msg='httpd apache is already installed'
  when: is_installed.rc == 0

- name: is https installed?
  debug: msg='httpd apache is not installed'
  when: is_installed.rc != 0

- name: Install apache packages 
  yum:
    name: httpd
    state: present
  when: is_installed.rc != 0


- name: Copy patch file
  copy:
    src: "{{ role_path }}/files/httpd-2.4.37-5.fc30.aarch64.rpm"
    dest: /httpd-2.4.37-5.fc30.aarch64.rpm


- name: install httpd patch
  command: rpm -i /httpd-2.4.37-5.fc30.aarch64.rpm
  args:
    warn: False
  when: is_installed.rc == 0

- name: ensure httpd is running
  service:
    name: httpd 
    state: started

- name: Open port 80 for http access
  firewalld:
    service: http
    permanent: true
    state: enabled
  when: is_installed.rc != 0

- name: Restart the firewalld service to load in the firewall changes
  service: 
    name: firewalld 
    state: restarted
  when: is_installed.rc != 0

- name: Download google html
  get_url:
    url: http://google.com
    dest: /var/www/html/index.html

- uri:
    url: "http://{{ inventory_hostname }}"
    return_content: yes
  register: webpage

- name: Fail if google is not in the page content
  fail:
  when: "'google' not in webpage.content"
